### ISSUE TITLE
Syrinscape Control playlist compatability

### ISSUE THREAD

**Issue by cwlithgow** [miriadis/svt#2]
This looks to be a compatabilty issue with the Syrinscape control module.

Traditional playlists high light the "now playing" item just fine:

![image](https://github.com/miriadis/svt/assets/85030999/5ae4db06-06bb-4320-91be-11ed5c1b173d)

Unfortunately playlists that are imported & played through Syrinscape Control module do not.

![image](https://github.com/miriadis/svt/assets/85030999/91cd2125-511f-42c9-bb70-f0bea075cefa)

I realize this is not necessarily that you could fix...but thought it worth noting.

**Comment by rmasoni** [comment]
It's nearly impossible for SVT to be the culprit here. The only thing the module does is to add a border and a shadow with CSS.

Have you tested without SVT to see if the issue persists?

**Comment by rmasoni** [comment]
I'll close this issue as there was no responde for a long time. Feel free to respond if it's still an issue!
