### ISSUE TITLE
DND5e Compatibility

### ISSUE THREAD

**Issue by M0nk3yy** [miriadis/svt#3]
Blind/private labels do not seem to work on recent dnd5e versions (3.0+ and Foundry v12). I presume this is due to system changes in the chat cards. Would be nice to have since it's a very useful module!

![image](https://github.com/user-attachments/assets/43799ff1-6733-4299-b0f3-15721c0ab614)

Only whispers seem to retain their tag.

**Comment by rmasoni** [comment]
Hey, I'm so sorry! GitHub didn't notify me by e-mail, so I missed this issue completely.

I believe I fixed it some time ago, look:

![ScreenShot 2024-11-22 at 02 59 42@2x](https://github.com/user-attachments/assets/544b4339-b066-413d-b2ee-eded41f47775)

Let me know if something else is still broken.
